openapi: 3.0.0
info:
  title: sophs-ecommerce deployed Copy
  contact:
    name: Ebune Daniel Yahya
    email: ebunedy@gmail.com
  version: "1.0"
servers:
  - url: https://sophdev.herokuapp.com/api/v1
    variables: {}
paths:
  /users/login:
    post:
      tags:
        - Users
      summary: login
      operationId: login
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/loginrequest"
            example:
              email: example@gmail.com
              password: password
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /users/register:
    post:
      tags:
        - Users
      summary: register
      operationId: register
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/registerrequest"
            example:
              firstName: ebune
              lastName: daniel
              email: example@gmail.com
              phoneNumber: "08120776546"
              password: password
              comfirmPassword: password
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /users:
    get:
      tags:
        - Users
      summary: get-all-users
      operationId: get-all-users
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /users/single-user:
    get:
      tags:
        - Users
      summary: get-single-user
      operationId: get-single-user
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /products/uploads:
    post:
      tags:
        - Products
      summary: image-upload
      operationId: image-upload
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /products:
    post:
      tags:
        - Products
      summary: create-product
      operationId: create-product
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/create-product-request"
            example:
              name: headset
              category: headset
              description: a good headset
              specification: product specification
              featured: false
              price: 6
              images:
                - https://res.cloudinary.com/sophdev/image/upload/v1657188985/file-upload/tmp-1-1657188982781.jpg
                - https://res.cloudinary.com/sophdev/image/upload/v1657189727/file-upload/tmp-2-1657189723524.jpg
              company: our company
              colors:
                - cyan
                - red
              freeShipping: false
              inventory: 20
              size:
                - m
                - xl
              user: 62b731103f4f
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
    get:
      tags:
        - Products
      summary: get-all-products
      operationId: get-all-products
      parameters:
        - name: search
          in: query
          description: ""
          required: true
          style: form
          explode: true
          schema:
            type: string
            example: men
        - name: sort
          in: query
          description: ""
          required: true
          style: form
          explode: true
          schema:
            type: string
            example: latest
        - name: category
          in: query
          description: ""
          required: true
          style: form
          explode: true
          schema:
            type: string
            example: women fashion
        - name: page
          in: query
          description: ""
          required: true
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            example: 1
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /products/62c6efb49360f:
    get:
      tags:
        - Products
      summary: get-single-product
      operationId: get-single-product
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /products/62c6efb49360f2224:
    patch:
      tags:
        - Products
      summary: update-product
      operationId: update-product
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/update-product-request"
            example:
              name: headset
              category: phone accessory
              description: a goood headset
              images:
                - https://res.cloudinary.com/sophdev/image/upload/v1657188985/file-upload/tmp-1-1657188982781.jpg
                - https://res.cloudinary.com/sophdev/image/upload/v1657189727/file-upload/tmp-2-1657189723524.jpg
              company: our company
              colors:
                - green
                - blue
              price: 6
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /products/62c6efb49360f2224d:
    get:
      tags:
        - Products
      summary: delete-product
      operationId: delete-product
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /reviews:
    post:
      tags:
        - reviews
      summary: create-review
      operationId: create-review
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/create-review-request"
            example:
              title: great product
              rating: 4
              comment: A great product, worth every penny I paid for
              product: 62c8038c551f16bfb1e
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
    get:
      tags:
        - reviews
      summary: get-all-reviews
      operationId: get-all-reviews
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /reviews/62cc0c3e0dd911d9035:
    get:
      tags:
        - reviews
      summary: get-single-review
      operationId: get-single-review
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
    patch:
      tags:
        - reviews
      summary: update-review
      operationId: update-review
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/update-review-request"
            example:
              title: great product
              rating: 4
              comment: A great product, worth every penny I paid for
              product: 62c8038c551f16bfb1e199b0
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /reviews/62cc0c3e0dd9:
    delete:
      tags:
        - reviews
      summary: delete-review
      operationId: delete-review
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
components:
  schemas:
    loginrequest:
      title: loginrequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: example@gmail.com
        password: password
    registerrequest:
      title: registerrequest
      required:
        - firstName
        - lastName
        - email
        - phoneNumber
        - password
        - comfirmPassword
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        password:
          type: string
        comfirmPassword:
          type: string
      example:
        firstName: ebune
        lastName: daniel
        email: example@gmail.com
        phoneNumber: "08120776546"
        password: password
        comfirmPassword: password
    create-product-request:
      title: create-product-request
      required:
        - name
        - category
        - description
        - specification
        - featured
        - price
        - images
        - company
        - colors
        - freeShipping
        - inventory
        - size
        - user
      type: object
      properties:
        name:
          type: string
        category:
          type: string
        description:
          type: string
        specification:
          type: string
        featured:
          type: boolean
        price:
          type: integer
          format: int32
        images:
          type: array
          items:
            type: string
          description: ""
        company:
          type: string
        colors:
          type: array
          items:
            type: string
          description: ""
        freeShipping:
          type: boolean
        inventory:
          type: integer
          format: int32
        size:
          type: array
          items:
            type: string
          description: ""
        user:
          type: string
      example:
        name: headset
        category: funiture
        description: a good headset
        specification: product specification
        featured: false
        price: 6
        images:
          - https://res.cloudinary.com/sophdev/image/upload/v1657188985/file-upload/tmp-1-1657188982781.jpg
          - https://res.cloudinary.com/sophdev/image/upload/v1657189727/file-upload/tmp-2-1657189723524.jpg
        company: our company
        colors:
          - cyan
          - red
        freeShipping: false
        inventory: 20
        size:
          - m
          - xl
        user: 62b731103f4f
    update-product-request:
      title: update-product-request
      required:
        - name
        - category
        - description
        - images
        - company
        - colors
        - price
      type: object
      properties:
        name:
          type: string
        category:
          type: string
        description:
          type: string
        images:
          type: array
          items:
            type: string
          description: ""
        company:
          type: string
        colors:
          type: array
          items:
            type: string
          description: ""
        price:
          type: integer
          format: int32
      example:
        name: headset
        category: phone accessory
        description: a goood headset
        images:
          - https://res.cloudinary.com/sophdev/image/upload/v1657188985/file-upload/tmp-1-1657188982781.jpg
          - https://res.cloudinary.com/sophdev/image/upload/v1657189727/file-upload/tmp-2-1657189723524.jpg
        company: our company
        colors:
          - green
          - blue
        price: 6
    create-review-request:
      title: create-review-request
      required:
        - title
        - rating
        - comment
        - product
      type: object
      properties:
        title:
          type: string
        rating:
          type: integer
          format: int32
        comment:
          type: string
        product:
          type: string
      example:
        title: great product
        rating: 4
        comment: A great product, worth every penny I paid for
        product: 62c8038c551f16bfb1e
    update-review-request:
      title: update-review-request
      required:
        - title
        - rating
        - comment
        - product
      type: object
      properties:
        title:
          type: string
        rating:
          type: integer
          format: int32
        comment:
          type: string
        product:
          type: string
      example:
        title: great product
        rating: 4
        comment: A great product, worth every penny I paid for
        product: 62c8038c551f16bfb1e199b0
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
security:
  - httpBearer: []
tags:
  - name: Users
  - name: Products
  - name: reviews
